[filetype]

rules = [
	# Hidden files
	{ url = "*", is = "hidden", fg = "darkgray" },
	{ url = "*/", is = "hidden", fg = "darkgray" },
	# Image
	{ mime = "**/image/*", fg = "yellow" },
	# Media
	{ mime = "**/{audio,video}/*", fg = "magenta" },
	# Archive
	{ mime = "**/application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "red" },
	# Document
	{ mime = "**/application/{pdf,doc,rtf}", fg = "cyan" },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "gray" },
	# Special file
	{ url = "*", is = "orphan", bg = "red" },
	{ url = "*", is = "exec", fg = "green" },
	# Dummy file
	{ url = "*", is = "dummy", bg = "red" },
	{ url = "*/", is = "dummy", bg = "red" },
	# Fallback
	{ url = "*/", fg = "blue" }
]

[mgr]
cwd = { fg = "gray" }

[tabs]
active   = { bg = "gray", bold = true }
inactive = { fg = "gray", bg = "darkgray" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { bg = "gray", bold = true }
normal_alt  = { fg = "gray", bg = "darkgray" }

[indicator]
padding = { open = " ", close = " " }

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

[which]
border = { fg = "gray" }
cand   = { fg = "gray" }

[confirm]
border = { fg = "gray" }
title  = { fg = "gray" }

[spot]
border   = { fg = "gray" }
title    = { fg = "gray" }
tbl_col  = { fg = "gray" }

[pick]
border = { fg = "gray" }

[input]
border = { fg = "gray" }

[cmp]
border = { fg = "gray" }

[tasks]
border = { fg = "gray" }

[help]
border = { fg = "gray" }